title: Reproductive Status Classifier
description: Show reproductive status (Reproductive or Sterile) of herbaria images using deep learning
about:


  This is a Herbaria Images Classifier using Deep Learning built on top of Tensorflow.


  The project was build by Yale University[https://github.com/TechForConservation/Herbarium]

sampleImages:
  - name: Reproductive
    url: https://bisque.cyverse.org/image_service/00-WjfW7XGwbHUWR8XNAgzLoU
  - name: Sterile
    url: https://bisque.cyverse.org/image_service/00-nzPSpnjjWoWwNDDR9LRMtG
